export const DASHBOARD_REQUEST = "DASHBOARD_REQUEST";
export const DASHBOARD_SUCCESS = "DASHBOARD_SUCCESS";
export const DASHBOARD_ERROR = "DASHBOARD_ERROR";

export const DATAMATRICES_REQUEST = "DATAMATRICES_REQUEST";
export const DATAMATRICES_REQUEST_SUCCESS = "DATAMATRICES_REQUEST_SUCCESS";
export const DATAMATRICES_REQUEST_ERROR = "DATAMATRICES_REQUEST_ERROR";

export const REMOVE_DATAMATRIX = "REMOVE_DATAMATRIX";
export const REMOVE_DATAMATRIX_FILTERED = "REMOVE_DATAMATRIX_FILTERED";

export const RESET_DATAMATRIX_NAME = "RESET_DATAMATRIX_NAME";

export const UPDATE_DATAMATRIX_CUSTOM_LABEL = "UPDATE_DATAMATRIX_CUSTOM_LABEL";

export const SAVED_MAPS_REQUEST = "SAVED_MAPS_REQUEST";
export const SAVED_MAPS_REQUEST_SUCCESS = "SAVED_MAPS_REQUEST_SUCCESS";
export const SAVED_MAPS_REQUEST_ERROR = "SAVED_MAPS_REQUEST_ERROR";


export const UPDATE_PANELS = "UPDATE_PANELS";
export const UPDATE_SELECTED_PLOT_OPTION = "UPDATE_SELECTED_PLOT_OPTION";
export const UPDATE_PROMPTS_AND_OPTIONS_GROUPED = "UPDATE_PROMPTS_AND_OPTIONS_GROUPED";
export const UPDATE_PROMPTS_AND_OPTIONS = "UPDATE_PROMPTS_AND_OPTIONS";
export const UPDATE_PROMPTS_GROUPED = "UPDATE_PROMPTS_GROUPED";

export const UPDATE_TABKEY_WIDGET_RECENT_SAVED = "UPDATE_TABKEY_WIDGET_RECENT_SAVED";
export const UPDATE_RECORDS_RESULT = "UPDATE_RECORDS_RESULT";

export const UPDATE_DATA_MATRIX_CONTENT = "UPDATE_DATA_MATRIX_CONTENT";






