export const UPDATE_TABKEY_LANDING = "UPDATE_TABKEY_LANDING";
export const TOGGLE_OFF_CANVAS_PROMPTS_LABELS = "TOGGLE_OFF_CANVAS_PROMPTS_LABELS";
export const TOGGLE_OFF_CANVAS_PROMPTS_INPUTS = "TOGGLE_OFF_CANVAS_PROMPTS_INPUTS";
export const UPDATE_TABKEY_LEFT_SIDEBAR = "UPDATE_TABKEY_LEFT_SIDEBAR";
export const UPDATE_TABKEY_IMPORT_TYPE = "UPDATE_TABKEY_IMPORT_TYPE";
export const SET_FAVOURITE_FIELD_GROUPED = "SET_FAVOURITE_FIELD_GROUPED";
export const FAVOURITE_FIELD_SAVE_REQUEST = "FAVOURITE_FIELD_SAVE_REQUEST";
export const SET_ANALYSIS_IN_PROGRESS = "SET_ANALYSIS_IN_PROGRESS";
export const SET_DATA_TABLE_COLUMNS = "SET_DATA_TABLE_COLUMNS";
export const SETUP_PROMPT_INPUT_WITH_OPTIONS = "SETUP_PROMPT_INPUT_WITH_OPTIONS";

export const GET_FIELD_AND_OPTIONS_REQUEST = "GET_FIELD_AND_OPTIONS_REQUEST";
export const GET_FIELD_AND_OPTIONS_ERROR = "GET_FIELD_AND_OPTIONS_ERROR";
export const GET_FIELD_AND_OPTIONS_SUCCESS = "GET_FIELD_AND_OPTIONS_SUCCESS";

export const GET_FIELD_AND_OPTIONS_REQUEST_WITHOUT_SERVICE = "GET_FIELD_AND_OPTIONS_REQUEST_WITHOUT_SERVICE";

export const SET_GROUPED_PROMPTS_AND_PROMPTS = "SET_GROUPED_PROMPTS_AND_PROMPTS";
export const SET_GROUPED_PROMPTS = "SET_GROUPED_PROMPTS";
export const SET_PROMPTS = "SET_PROMPTS";

export const GET_PROMPT_OPTIONS_REQUEST = "GET_PROMPT_OPTIONS_REQUEST";
export const GET_PROMPT_OPTIONS_ERROR = "GET_PROMPT_OPTIONS_ERROR";
export const GET_PROMPT_OPTIONS_SUCCESS = "GET_PROMPT_OPTIONS_SUCCESS";

export const SET_PROMPT_SELECTION_BADGES = "SET_PROMPT_SELECTION_BADGES";


export const SAVE_CONFIG_REQUEST = "SAVE_CONFIG_REQUEST";
export const SAVE_CONFIG_ERROR = "SAVE_CONFIG_ERROR";
export const SAVE_CONFIG_SUCCESS = "SAVE_CONFIG_SUCCESS";

export const LOAD_CONFIG_REQUEST = "LOAD_CONFIG_REQUEST";
export const LOAD_CONFIG_ERROR = "LOAD_CONFIG_ERROR";
export const LOAD_CONFIG_SUCCESS = "LOAD_CONFIG_SUCCESS";

export const SET_CONFIG = "SET_CONFIG";

export const SET_PLEASE_WAIT = "SET_PLEASE_WAIT";


export const SET_GENERAL_CONFIG = "SET_GENERAL_CONFIG";
export const SET_GENERAL_CONFIGS = "SET_GENERAL_CONFIGS";

export const SET_MMM_OPTIONS = "SET_MMM_OPTIONS";



export const DASHBOARD_ERROR = "DASHBOARD_ERROR";
export const DASHBOARD_SUCCESS = "DASHBOARD_SUCCESS";
export const CHANGE_THEME = "CHANGE_THEME";

export const SET_FLASH_TOAST = "SET_FLASH_TOAST";


