export const UPDATE_TABKEY_FIELDS = "UPDATE_TABKEY_FIELDS";
export const UPDATE_SELECTED_FIELD = "UPDATE_SELECTED_FIELD";
export const UPDATE_TABKEY_ACTIVE_INPUT = "UPDATE_TABKEY_ACTIVE_INPUT";
export const UPDATE_MAP_ZOOM = "UPDATE_MAP_ZOOM";
export const UPDATE_MAP_LONG = "UPDATE_MAP_LONG";
export const UPDATE_MAP_LAT = "UPDATE_MAP_LAT";
export const UPDATE_XY = "UPDATE_XY";
export const TOGGLE_LEGEND_TOOLTIP = "TOGGLE_LEGEND_TOOLTIP";
export const UPDATE_LEGEND = "UPDATE_LEGEND";
export const UPDATE_VALUE_TOOLTIP = "UPDATE_VALUE_TOOLTIP";
export const UPDATE_OFFSET_TOOLTIP = "UPDATE_OFFSET_TOOLTIP";
export const UPDATE_BACKGROUND_TOOLTIP = "UPDATE_BACKGROUND_TOOLTIP";
export const UPDATE_SCALE_TYPE = "UPDATE_SCALE_TYPE";
export const UPDATE_MAP_VALUE = "UPDATE_MAP_VALUE";
export const UPDATE_AGGREGATION_VALUE = "UPDATE_AGGREGATION_VALUE";
export const TOGGLE_SHOW_DATA_POINTS = "TOGGLE_SHOW_DATA_POINTS";
export const TOGGLE_SHOW_GRID = "TOGGLE_SHOW_GRID";
export const TOGGLE_IS_DRAWING_GEO_FILTER = "TOGGLE_IS_DRAWING_GEO_FILTER";
export const UPDATE_GEO_FILTER_BOX = "UPDATE_GEO_FILTER_BOX";
export const SET_FILTER = "SET_FILTER";
export const SET_TOTAL_RECORD = "SET_TOTAL_RECORD";
export const SET_IS_MAP_REFRESH_DUE = "SET_IS_MAP_REFRESH_DUE";
export const SET_LAST_MAP_RESET_TIME = "SET_LAST_MAP_RESET_TIME";
export const SET_MAP_BOUND_COORD = "SET_MAP_BOUND_COORD";




export const SET_CREATE_MAP_STEP1_PROMPT_OPTIONS = "SET_CREATE_MAP_STEP1_PROMPT_OPTIONS";
export const SET_CREATE_MAP_STEP1_SELECTED_PROMPT = "SET_CREATE_MAP_STEP1_SELECTED_PROMPT";

export const SET_OPTIONS = "SET_OPTIONS";

export const LOAD_OPTIONS = "LOAD_OPTIONS";
export const LOAD_OPTIONS_SUCCESS = "LOAD_OPTIONS_SUCCESS";
export const LOAD_OPTIONS_ERROR = "LOAD_OPTIONS_ERROR";


export const TOGGLE_OFF_CANVAS_PROMPTS_LABELS = "TOGGLE_OFF_CANVAS_PROMPTS_LABELS";
export const TOGGLE_OFF_CANVAS_PROMPTS_INPUTS = "TOGGLE_OFF_CANVAS_PROMPTS_INPUTS";
export const SET_STEP1_PROMPTS = "SET_STEP1_PROMPTS";
export const SET_QUALIFY_FILTER_STEP1_PROMPTS = "SET_QUALIFY_FILTER_STEP1_PROMPTS";
export const SET_SELECTED_SAVED_MAP_ID = "SET_SELECTED_SAVED_MAP_ID";


export const LOAD_MAP = "LOAD_MAP";
export const LOAD_MAP_SUCCESS = "LOAD_MAP_SUCCESS";
export const LOAD_MAP_ERROR = "LOAD_MAP_ERROR";


export const SET_SAVED_MAP = "SET_SAVED_MAP";
export const SET_PLOT_RECORDS = "SET_PLOT_RECORDS";
// export const SAVE_HOME_VIEW_CONFIG_REQUEST = "SAVE_HOME_VIEW_CONFIG_REQUEST";
export const TOGGLE_MAP_VIEW = "TOGGLE_MAP_VIEW";

export const SET_IS_MAP_SAVED = "SET_IS_MAP_SAVED";