export const DEFAULT = "DEFAULT";
export const DATAMATRICES_REQUEST = "DATAMATRICES_REQUEST";
export const DATAMATRICES_REQUEST_SUCCESS = "DATAMATRICES_REQUEST_SUCCESS";
export const DATAMATRICES_REQUEST_ERROR = "DATAMATRICES_REQUEST_ERROR";
export const FAVOURITE_FIELD_SAVE_REQUEST = "FAVOURITE_FIELD_SAVE_REQUEST";
export const FAVOURITE_FIELD_SAVE_REQUEST_ERROR = "FAVOURITE_FIELD_SAVE_REQUEST_ERROR";
export const FAVOURITE_FIELD_SAVE_REQUEST_SUCCESS = "FAVOURITE_FIELD_SAVE_REQUEST_SUCCESS";
export const CHANGE_SELECTED_MATRICE = "CHANGE_SELECTED_MATRICE";




export const SET_GROUPED_PROMPT_LABELS = "SET_GROUPED_PROMPT_LABELS";
export const SET_PROMPT_OPTIONS = "SET_PROMPT_OPTIONS";


export const SET_SELECTED_FIELD = "SET_SELECTED_FIELD";


export const LOAD_GROUPED_PROMPT_REQUEST = "LOAD_GROUPED_PROMPT_REQUEST";
export const LOAD_GROUPED_PROMPT_REQUEST_SUCCESS = "LOAD_GROUPED_PROMPT_REQUEST_SUCCESS";
export const LOAD_GROUPED_PROMPT_REQUEST_ERROR = "LOAD_GROUPED_PROMPT_REQUEST_ERROR";

export const SET_GROUPED_PROMPT_REQUEST = "SET_GROUPED_PROMPT_REQUEST";